# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0004_auto_20161023_0204'),
    ]

    operations = [
    ]
