# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0006_auto_20161023_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='item',
        ),
        migrations.AddField(
            model_name='master',
            name='item',
            field=models.ManyToManyField(to='pop.Item'),
        ),
    ]
