# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0008_statistic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistic',
            new_name='Statistics',
        ),
    ]
