# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0009_auto_20161026_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='item',
            field=models.ManyToManyField(related_name='item', to='pop.Item'),
        ),
    ]
