# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0010_auto_20161026_1745'),
    ]

    operations = [
    ]
