# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0011_auto_20161028_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='item',
        ),
        migrations.AddField(
            model_name='master',
            name='item',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='pop.Item'),
            preserve_default=False,
        ),
    ]
